export const BitPerms = {
  templateName: 1n << 0n,
  layout: 1n << 1n,
  profilePicture: 1n << 2n,
  jobTitle: 1n << 3n,
  coverPhoto: 1n << 4n,
  companyLogo: 1n << 5n,
  company: 1n << 6n,
  location: 1n << 7n,
  bio: 1n << 8n,
  colorTheme: 1n << 9n,
  linkColor: 1n << 10n,
  matchLinkIconsToTheme: 1n << 11n,
  font: 1n << 12n,
  links: 1n << 13n,
  connectButtonLabel: 1n << 14n,
  formDisclaimer: 1n << 15n,
  allowNonAdminsToUse: 1n << 16n,
  name: 1n << 17n,
  qrcolor: 1n << 18n,
  qrcustomlogo: 1n << 19n,
  exportleadcrm: 1n << 20n,
  downloadleads: 1n << 21n,
  downloadleadascontact: 1n << 22n,
  exportanalitics: 1n << 23n,
  emailsign: 1n << 24n,
  virtualbackground: 1n << 25n,
  createnewcard: 1n << 26n,
  switchcard: 1n << 27n,
  accountmail: 1n << 28n,
  followupmail: 1n << 29n,
  text: 1n << 30n,
  call: 1n << 31n,
  email: 1n << 32n,
  contactcard: 1n << 33n,
  adress: 1n << 34n,
  facetime: 1n << 35n,
  whatsapp: 1n << 36n,
  instagram: 1n << 37n,
  linkedin: 1n << 38n,
  facebook: 1n << 39n,
  youtube: 1n << 40n,
  twitter: 1n << 41n,
  tiktok: 1n << 42n,
  snapchat: 1n << 43n,
  twitch: 1n << 44n,
  pinterest: 1n << 45n,
  wechat: 1n << 46n,
  discord: 1n << 47n,
  telegram: 1n << 48n,
  thread: 1n << 49n,
  clubhouse: 1n << 50n,
  website: 1n << 51n,
  calendly: 1n << 52n,
  calendlyembed: 1n << 53n,
  rewiews: 1n << 54n,
  etsy: 1n << 55n,
  applimk: 1n << 56n,
  chillpaper: 1n << 57n,
  msbookings: 1n << 58n,
  booksy: 1n << 59n,
  square: 1n << 60n,
  yelp: 1n << 61n,
  teamdirectory: 1n << 62n,
  embedvideo: 1n << 63n,
  textsection: 1n << 64n,
  file: 1n << 65n,
  dropdown: 1n << 66n,
  featured: 1n << 67n,
  customlink: 1n << 68n,
  zillow: 1n << 69n,
  cashapp: 1n << 70n,
  venmo: 1n << 71n,
  paypal: 1n << 72n,
  zelle: 1n << 73n,
  spotify: 1n << 74n,
  applemusic: 1n << 75n,
  soundcloud: 1n << 76n,
  podcats: 1n << 77n,
  poshmark: 1n << 78n,
  mediakits: 1n << 79n,
  opensea: 1n << 80n,
  hoobe: 1n << 81n,
  linktree: 1n << 82n,
} as const;

export const PermissionGroups = {
  about: [
    "profilePicture",
    "jobTitle",
    "colorTheme",
    "companyLogo",
    "location",
    "bio",
    "name",
  ],
  content: [
    "text",
    "call",
    "email",
    "contactcard",
    "adress",
    "facetime",
    "whatsapp",
    "instagram",
    "linkedin",
    "facebook",
    "youtube",
    "twitter",
    "tiktok",
    "snapchat",
    "twitch",
    "pinterest",
    "wechat",
    "discord",
    "telegram",
    "thread",
    "clubhouse",
    "website",
    "calendly",
    "calendlyembed",
    "rewiews",
    "etsy",
    "applimk",
    "chillpaper",
    "msbookings",
    "booksy",
    "square",
    "yelp",
    "teamdirectory",
    "embedvideo",
    "textsection",
    "file",
    "dropdown",
    "featured",
    "customlink",
    "zillow",
    "cashapp",
    "venmo",
    "paypal",
    "zelle",
    "spotify",
    "applemusic",
    "soundcloud",
    "podcats",
    "poshmark",
    "mediakits",
    "opensea",
    "hoobe",
    "linktree",
  ],
  qrcode: ["qrcolor", "qrcustomlogo"],
  settings:[
    "exportleadcrm",
    "downloadleads",
    "downloadleadascontact",
    "exportanalitics",
    "emailsign",
    "virtualbackground",
    "createnewcard",
    "switchcard",
    "accountmail",
    "followupmail",
  ],
  // Diğer gruplar...
} as const;
export const getPermissionsByGroup = (
  group: keyof typeof PermissionGroups
): bigint[] => {
  return PermissionGroups[group].map((key) => BitPerms[key]);
};
export const hasPermission = (userPerms: bigint, perm: bigint): boolean => {
  return (userPerms & perm) === perm;
};
